### ISSUE TITLE
Some demo URI are not working

### ISSUE THREAD

**Issue by ronindesign** [Krisseck/Hashtag-Wall-Server#10]
Trying to test the demo, but API calls involving `delete` functionality are not working (loading forever and then failing).
Some URI tested:
- http://hashtag.polso.info:8080/admin/delete/27828
- http://hashtag.polso.info:8080/admin/deleted-posts

Looks like first commit was last month, so I'm assuming things are just not fully working!

Let me know if I can be of assistance. Would love to use this at my wedding in a few months. :)

EDIT: It also appears as tho I'm unable to scroll on the demo "client" web page.

**Comment by Krisseck** [comment]
Thanks for the report! I needed to update the demo site, it is working now.

Regarding the lack of scroll: this is deliberate, it's meant for static display monitors and scrolling is disabled so that you don't accidentally scroll it. This can be easily enabled in the CSS, just remove the line `overflow: hidden;` from `body`.
